spring.application.name=BudowaKosztorysu

spring.datasource.url=jdbc:h2:mem:kosztorysy
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.security.user.name=admin
spring.security.user.password=admin
spring.flyway.enabled=false

google.translate.api-key=${GOOGLE_TRANSLATE_API_KEY:}